services:

##########################################
##
## kanban-flow / bootstrap front end
##
##########################################

    kanban-flow-web:

        container_name: kanban-flow-web

        image: softwareshinobi/kanban-flow-web:intranet

        build: 

            context: web

            dockerfile: Dockerfile

        ports:

            - "10.28.1.1:8880:80"

##########################################
##
## kanban-flow / spring rest back end
##
##########################################

    kanban-flow-api:

        container_name: kanban-flow-api
        
        image: softwareshinobi/kanban-flow-api:intranet

        build: 

            context: .

            dockerfile: Dockerfile

        depends_on:

           - kanban-flow-database
    
        restart: unless-stopped

        ports:

            - "10.28.1.1:8888:8888"

        environment:

            DB_HOST: kanban-flow-database

            DB_NAME: valorant_digital_workspace

            DB_USER: valorant_digital_workspace

            DB_PASS: valorant_digital_workspace

##########################################
##
## kanban-flow / documentation
##
##########################################

    kanban-flow-docs:

        container_name: kanban-flow-docs

        image: softwareshinobi/kanban-flow-docs:intranet

        build: 

            context: docs

            dockerfile: Dockerfile

        ports:

            - "10.28.1.1:8889:80"
