services:

   valorant-digital-workspace-web:

        container_name: valorant-digital-workspace-web

        image: softwareshinobi/valorant-digital-workspace-web

        build: 

            context: .

            dockerfile: Dockerfile

        ports:

            - 4444:80

        environment:

            VIRTUAL_HOST: mateomontenegro.online

            LETSENCRYPT_HOST: mateomontenegro.online

