services:

   web:

        container_name: web

        image: web

        build: 

            context: .

            dockerfile: Dockerfile

        ports:

            - 4444:80

        environment:

            VIRTUAL_HOST: mateomontenegro.online

            LETSENCRYPT_HOST: mateomontenegro.online
